### ISSUE TITLE
Removing a repo seems broken in 1.3.9

### ISSUE THREAD

**Issue by NathanaelA** [boyter/searchcode-server#102]
I misnamed a repo; so I went to delete it.  It shows it is queued to delete but it doesn't delete it even after adding and restarting server...  Just shows it as pending delete...

**Comment by boyter** [comment]
Yep its one of those things that needs improvement I have it flagged here https://github.com/boyter/searchcode-server/issues/41

Generally if you click delete when the job is indexing it will wait till the job is finished before removing it.

Can you try clicking delete and then waiting for a while. It should clean up when the indexing is finished. If you restart after clicking delete the delete queue will be flushed and the delete operation will be forgotten. In short waiting is the best option for the moment.

TODO - Store pending deletes in a persistant queue and apply it on startup.
TODO - Increase priority of issue 41.

**Comment by NathanaelA** [comment]
Yeah, I saw #41 issue; the machine is sitting doing nothing at the moment.  The machine still shows one repo to be deleted (on the dashboard).     It has been this way for the last 40 minutes according to the dash board...  

![image](https://cloud.githubusercontent.com/assets/850871/25601113/34c6e15c-2eaf-11e7-94a3-053abfc3d9b7.png)

**Comment by NathanaelA** [comment]
Actually it was a stupid permissions issue; sorry for the false report...   When I copied it out of the .tar.gz file; apparently the main "release" folder was tagged as a different user.  Everything else was tagged correctly, so I didn't notice it until I went up the chain to the top of the directory structure...

**Comment by boyter** [comment]
No problem. Still going to implement the todo's I have, but will move then to #41
