### ISSUE TITLE
File Statistics is based on count of files; any way to make this based on file size.

### ISSUE THREAD

**Issue by NathanaelA** [boyter/searchcode-server#103]
For example; in one of my repos I have a ton of small files; most of them like documentation there are two or more of.  However, there is only ONE Large JavaScript file.      SearchCode insists the JS code is only 12% of the repo.  Where if you count file sizes of the repo; JS would end up being over 50% of the project.

**Comment by boyter** [comment]
Thats actually a better way of calculating the size. Sounds like a good enhancement.

**Comment by boyter** [comment]
https://i.imgur.com/WLDHoNN.png

Example how this in practice.

**Comment by boyter** [comment]
Merged into master.
