### ISSUE TITLE
Any easy way to eliminate files from being indexed / counted

### ISSUE THREAD

**Issue by NathanaelA** [boyter/searchcode-server#104]
I have no interest in having the "license", ".gitignore" and ".npmignore", and ".json" counted in the repo sizes, is there a easy way to have it ignore these file types.

**Comment by boyter** [comment]
Just to note, that will exclude them from being indexed as well. The count is based on the index so thats what this will actually achieve. 

I have a branch to add reports to searchcode where these sort of things would be controlled at runtime, but that is probably a major release away at this point.

**Comment by NathanaelA** [comment]
Yeah, I don't want them to show up at all; they really are pointless files for searching at least in the eco-system I'm working with.      ;-)

**Comment by boyter** [comment]
That will do it then. The blacklist is only by file extention at the moment, but the fact that is would pick up .gitignore and .npmignore is more of a hack.

TODO - Add filename filter.

**Comment by boyter** [comment]
Going to close this and merge with https://github.com/boyter/searchcode-server/issues/105 as it is the same issue.
