### ISSUE TITLE
Start Scripts

### ISSUE THREAD

**Issue by NathanaelA** [boyter/searchcode-server#106]
Just so you can include some samples with your app; for others...  :grinning:
I have SearchCode installed in /opt/searchcode

Ubuntu 14.04 - Upstart searchcode.conf file 
```
description "Search Code Server"
author      "Nathanael Anderson"

start on (local-filesystems and net-device-up IFACE!=lo)
stop on shutdown

chdir /opt/searchcode
limit nofile 999999 999999
respawn

script
    exec /usr/bin/java -jar searchcode-1.3.9.jar > /var/log/searchcode.log 2>&1
end script
```

Systemd (Ubuntu 15+) searchcode.service file.
```
[Unit]
Description=SearchCode Server

[Service]
WorkingDirectory=/opt/searchcode
ExecStart=/usr/bin/java -jar searchcode-1.3.9.jar
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by boyter** [comment]
Will include these into the KB and readme. Thank you for providing them.

**Comment by boyter** [comment]
https://searchcodeserver.com/knowledge-base/upstart-and-systemd-startup-scripts-for-ubuntu.html
