### ISSUE TITLE
Cannot have / and possibly other characters in repo name

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#108]
In example repo set with name like Scripts-[Stash/CAF] will end up:
* not being able to browse http://localhost:8080/repository/overview/Scripts-[Stash/CAF]/ returns 404 due to not translated / in []
* not being able to delete either (had to do this via sqlite manager)

**Comment by boyter** [comment]
Sitting in master is some logic to check this. Still needs to be enforced server side (this requires API changes as well) but at least the names are raised when adding though the add page.

**Comment by boyter** [comment]
Now enforced through the application entrypoints that add repositories.

**Comment by quasarea** [comment]
thanks a lot, seen you allowed _ as well, what about the dot?

**Comment by boyter** [comment]
I noticed someone else needed _ so yes I added that. At the moment . is not allowed. I am planning on reworking a lot of what was done in the backend to allow any characters to be supported in the future. Just need to nut out the details.

**Comment by quasarea** [comment]
I could use namespaces as repository names, will suffer quietly without it (or update sqlite) ;p

**Comment by boyter** [comment]
That may work as well. Keep in mind that the next release should remove this restriction totally.
