### ISSUE TITLE
Add ability to reindex single repo

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#109]
Would be great if we could manually trigger reindexing for single repo from http://localhost:8080/admin/repolist/

this could be also used to hook up triggered reindexing, i.e. have a file change monitor that calls http://localhost:8080/admin/repolist/MyRepository/?reindex to force reindexing of file change (but would require flag like "manual reindex" to stop reindexing via timers:
```
check_repo_chages=600
check_filerepo_chages=14400
```
btw. seems like there is 'n' missing for those settings, isn't it?

**Comment by boyter** [comment]
Sounds reasonable. And yes, that looks like a typo.

**Comment by boyter** [comment]
Currently logic to do this is sitting in branch newindex. Still need to work out the scheduling of the index to make this happen though.

**Comment by boyter** [comment]
Going to do this by setting its last index time to -200 years then add it to the list to be indexed. This will force it to be fully reprocessed and clean up the index at the same time.

**Comment by boyter** [comment]
This is also in master @quasarea so feel free to check it out when you finish your break :) Might help with checking #110 actually.

**Comment by boyter** [comment]
This is also in master @quasarea so feel free to check it out when you finish your break :) Might help with checking #110 actually.
