### ISSUE TITLE
Evaluate reindexing behaviour

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#110]
I have few file repos that weren't indexed since I started server a week ago.

At http://localhost:8080/repository/list those are always "Indexing...", there is a file count > 0 at the end of the row. 

It seems like I can't get the results from them at all, what would mean that they were never actually fully indexed and merged to main index.

I think timer controlled by variable like `check_filerepo_chages` may cause reindexing without finishing/merging the index in a first step.

**Comment by quasarea** [comment]
It looks like that switching from low_memory=true and 10 file indexers to low_memory=false and single file indexed did some progress there so it may be actually related to #85

**Comment by boyter** [comment]
Yeah there is some iffy logic I am looking to resolve currently. Still work in progress at this point though.

**Comment by boyter** [comment]
This should hopefully go away with the newer index that is sitting on the branch newindex. Still working out the issues with that though.

**Comment by boyter** [comment]
@quasarea Would it be possible for you to take the latest version from master build it and try it out again? I believe this should be resolved for you now with the latest changes.

**Comment by quasarea** [comment]
After 4th, on holiday now. Cheers

On 24 Aug 2017 09:36, "Ben Boyter" <notifications@github.com> wrote:

@quasarea <https://github.com/quasarea> Would it be possible for you to
take the latest version from master build it and try it out again? I
believe this should be resolved for you now with the latest changes.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/boyter/searchcode-server/issues/110#issuecomment-324557851>,
or mute the thread

**Comment by boyter** [comment]
@quasarea No problem.

**Comment by boyter** [comment]
@quasarea So its a bit past the 4th. Any chance to have had a look at this?

**Comment by quasarea** [comment]
just started indexing in 1.3.11 build from sources. will keep you in loop

**Comment by quasarea** [comment]
just started indexing in 1.3.11 build from sources. will keep you in loop

**Comment by quasarea** [comment]
updated in #85, we should close one as a duplicate as indeed they are about the same issue

**Comment by boyter** [comment]
Closing due to being duplicate.
