### ISSUE TITLE
log output from multiple threads

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#112]
currently log output from multiple threads is hard to gasp, 
would be great to have some distinction, in example like in Jenkins, where output from different threads start with [threadName]: 

this applies to main thread, git and file threads as well

**Comment by boyter** [comment]
Pretty easy to add I suppose. Having a greater grasp of what is happening when the server is running is something I do want to improve at some point as well.

**Comment by boyter** [comment]
Done. Going to close this down.
