### ISSUE TITLE
Git repo not working correctly

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#113]
Did it in past and it worked, now I follow https://searchcodeserver.com/knowledge-base/how-to-add-a-repository-to-the-index.html to add an repo and I end up with C:\searchcode\current\repo folder with MyGitRepoName subfolder that has contains only:
* .git
* searchcode.cloneupdate.success
* searchcode.index.success

Doing git pull for such folder results:
git.exe pull -v --progress "origin"
```
warning: redirecting to https://stash.myCompany.com/scm/myTeam/repo.git/
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master
```
with tortoise GIT pull I'm getting:
```
warning: redirecting to https://stash.myCompany.com/scm/myTeam/repo.git/
POST git-upload-pack (163 bytes)
remote: Counting objects: 1383, done.
remote: Compressing objects: 100% (1379/1379), done.
remote: Total 1383 (delta 900), reused 0 (delta 0)
Receiving objects: 100% (1383/1383), 211.86 KiB | 0 bytes/s, done.
Resolving deltas: 100% (900/900), done.
From http://stash.myCompany.com/scm/myTeam/repo
* [new branch]      master     -> origin/master
You asked to pull from the remote 'origin', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.

git did not exit cleanly (exit code 1) (3167 ms @ 16/05/2017 11:32:26)
```

seems like it is not setting correct branch (master) anymore

**Comment by boyter** [comment]
This would be using the external git?

**Comment by quasarea** [comment]
true, haven't thought about this. let me try with internal

**Comment by quasarea** [comment]
Ok it seems to be my issue, it works with external repositories, will follow up when manage to find the issue, but you can close this

**Comment by quasarea** [comment]
ok, so its about ssl certificate not valid, I already forced git to deal with it ages ago, but it seems, that there is something else relying on it. The only configuration that works is if I do https location and http source:
* Repository Location: http**s**://stash.myCompany.com/scm/myTeam/repo.git
* Repository Source: http://stash.myCompany.com/scm/myTeam/repo
this works fine, making both http or https will not work in my case.

**Comment by boyter** [comment]
Interesting. The source should just link back, so very odd that you experienced this.
