### ISSUE TITLE
Filter in /html does not work properly

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#120]
Same query, same filter yields different results:
15 hits - `http://localhost:8080/?q=%22Microsoft.Office.Interop.Excel%22&lan=MSBuild%20scripts`
0 hits - `http://localhost:8080/html?q=%22Microsoft.Office.Interop.Excel%22&lan=MSBuild%20scripts`

I noticed that in even result address gets different, maybe related to space in language name:
`http://localhost:8080/?q=%22Microsoft.Office.Interop.Excel%22&lan=MSBuild%20scripts`
`http://localhost:8080/html/?q=%22Microsoft.Office.Interop.Excel%22&lan=MSBuild+scripts`

**Comment by boyter** [comment]
As you guessed it is because of the space. I changed the way that was handled to fix a bug on the JS side and looks like it was not reflected on the HTML.

TODO - Improve integration tests to cater for this to avoid it reoccurring and then fix the bug.
