### ISSUE TITLE
Allow forward slashes as part of repository names (to group repositories)

### ISSUE THREAD

**Issue by sschuberth** [boyter/searchcode-server#122]
In [Gerrit](https://www.gerritcodereview.com/), repositories are usually grouped by applying a common "namespace" prefix. Namespaces are separated by forward slashes, similar to Linux paths. As an example see e.g. the list at https://gerrit-review.googlesource.com/#/admin/projects/?filter=%255E.*%252F.*%2524:

    apps/reviewit
    libs/modules/repomanager/cassandra
    plugins/admin-console
    plugins/analytics
    ...

When indexing such repositories, it would be nice if searchcode would either (at the example of `apps/reviewit`):

- support forward slashes as part of the name, i.e. use the literal string "apps/reviewit" as the name, or
- understand the semantics of a forward slash and use "reviewit" as the repository name and use "apps" to somehow group the repository (along with others in the same namespace).

**Comment by boyter** [comment]
So the reason was that when searchcode clones or checks out source code it puts it into the ./repo/ directory with the name that was supplied as the folder to check out into. Initially it did support any character but this caused issues for some filesystems and resulted in a lot of checking code to handle it.

I am in the middle of designing out a more flexible backend which would support this though. 

Is this a deal breaker that is stopping you from being able to use searchcode?

**Comment by sschuberth** [comment]
Well, I believe we have found a work-around for that issue meanwhile.

But another (not really related) issue is that the branch name needs to be an explicit part of the name, too, as otherwise adding a new repository with the same name but a different branch would silently overwrite an already existing entry with the same repository name.

While that somewhat works, too, it lowers Searchcode's rank in our evaluation of code search tools 😉

**Comment by boyter** [comment]
Yep this is something else that would be catered for with the new backend design I am working on. It will probably be the main focus of the next release.

**Comment by sschuberth** [comment]
Thanks for the information. Any ETA for that next release?

**Comment by boyter** [comment]
So the current one 1.3.10 will probably be pushed out this week, I just need to finish running through the usual suite of tests to ensure that everything works as expected. I like to leave this running for at least 3 days to be confident.

Work will then start on the next release, which I expect to to be pushed out a month or so later as there is usually a release every month or so.

**Comment by boyter** [comment]
Release 1.3.10 has been pushed out. The focus for 1.3.11 will be stability of the indexing and a reworked backend system for the repositories.

**Comment by boyter** [comment]
Probably going to have to cut this from the next release I think. Getting the new indexing engine working was a larger task then anticipated. It did produce some other nice functionality but to add this as well will slow the release of it down even more.

Going to push out to 1.3.12

**Comment by sschuberth** [comment]
Thanks for reporting back about the status in any case!

**Comment by boyter** [comment]
I am still sorry about it though. I did want include it. Its going to be the main focus of the next release though. Once again sorry about that.

**Comment by sschuberth** [comment]
@boyter, any update on the ETA for that next release?

**Comment by boyter** [comment]
@sschuberth Ah right. Actually it was pushed out a few days ago, however this one fell by the wayside. 

Mostly due to trying to track down and resolve this annoying bug https://github.com/boyter/searchcode-server/issues/168 which really needed to be resolved.

However due to the tweaks I made in order to support https://github.com/boyter/searchcode-server/issues/162 this should be easier to implement. Going to make this 100% focus over the next few days of development effort.

**Comment by boyter** [comment]
Current plan is to allow any characters for the project name. This will allow the / to be added as part of the name. However on adding of a project another name will be added which will be with the invalid ones stripped and a hash added on the end. This is what will be used for filesystem operations while the other remains.

Currently its not possible to rename a project so this approach should work without issue.

**Comment by boyter** [comment]
So this has been merged into master. Still needs testing to verify that everything works as expected. Have checked that file and git repositories are indexed correctly. Need to try out SVN for completeness.
Additional tests would be useful.

Identified bugs so far,

- Link to repository on search page is broken

**Comment by boyter** [comment]
Have resolved a few small issues that have come out of this mostly due to having to escape things correctly. This appears to work correctly for all GIT and File repositories I have tried.

**Comment by sschuberth** [comment]
Thank you!

**Comment by boyter** [comment]
No problem. Just need to investigate SVN more closely before marking it as done.

**Comment by sschuberth** [comment]
Hi @boyter, did you have a chance to look at SVN yet to close this issue for good?

**Comment by boyter** [comment]
I have looked at it. SVN appears to be fine. However not ready to close this down yet as there are some other subtle bugs I am tracking down due to this change. All appears to be stable but just need to put some test cases in to catch those issues first.

**Comment by ttgirod** [comment]
Hi  @boyter,

> So this has been merged into master. Still needs testing to verify that everything works as expected

Checking this in the latest build created from the master branch, there seem to be still some issues with repositories containing forward slashes in their names. 
E.g. if you set the Repository Name to "test/test-1", such a repository would be added successfully, but trying to access it via `<searchcode-server-url>/admin/repo/edit/test/test-1/` would give you the following error:

`INFO spark.http.matching.MatcherFilter - The requested route [/admin/repo/edit/test/test-1/] has not been mapped in Spark for Accept: [text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8]`

**Comment by boyter** [comment]
Had a feeling I would have missed a route or two. Hence waiting for more testing. Will resolve the above as soon as possible.

**Comment by ttgirod** [comment]
Hi  @boyter,

> So this has been merged into master. Still needs testing to verify that everything works as expected

Checking this in the latest build created from the master branch, there seem to be still some issues with repositories containing forward slashes in their names. 
E.g. if you set the Repository Name to "test/test-1", such a repository would be added successfully, but trying to access it via `<searchcode-server-url>/admin/repo/edit/test/test-1/` would give you the following error:

`INFO spark.http.matching.MatcherFilter - The requested route [/admin/repo/edit/test/test-1/] has not been mapped in Spark for Accept: [text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8]`

**Comment by boyter** [comment]
Currently trying this out with SVN to ensure all code paths work. Going to increase the code coverage of the tests to help with this as well.

**Comment by ttgirod** [comment]
> @ttgirod Have resolved that route for you. Just pull the latest and build.

@boyter Yes, that looks a way better now, thanks for fixing it!

**Comment by sschuberth** [comment]
Thanks for checking this @ttgirod!

**Comment by ttgirod** [comment]
> @ttgirod Have resolved that route for you. Just pull the latest and build.

Except that now I found one more place where it still fails from...

Trying to access the following URL (e.g. from the search results): 
http://searchcode-server-url/repository/overview/test-projects/test-1/
still throws an error like:
`[qtp686802431-65] INFO spark.http.matching.MatcherFilter - The requested route [/repository/overview/test-projects/test-1/] has not been mapped in Spark for Accept: [text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8]`

**Comment by boyter** [comment]
No problem. Will have a look into that. Not surprised you found a few more of these.  Ill have a fix ready sometime in the next 24 hours.

**Comment by boyter** [comment]
@ttgirod That route should be resolved as well. Thanks for taking the time to find these and let me know about them. They are usually simple fixes but can be a pain to find.

**Comment by sschuberth** [comment]
@boyter Thanks for making these timely fixes. One thing that I'm also seeing with Gerrit is that "Filter Owners" only offers "Unknown". Can this be somehow related to the slashes issue, as SearchCode might not be able to "git blame" (or whatever mechanism it uses) these repos?

**Comment by boyter** [comment]
@sschuberth The only way searchcode can determine the owner is if it is a git or svn repository. Any file repository will have all the files listed as having an unknown owner.

I did debate removing it when in these situations, but decided against it as it made some of the UI needlessly complex. Especially when you consider that there may be a mix of repositories or that the name might indeed be Unknown. A quick thought is that perhaps if all the repositories are File based ones then I could disable the filter, or perhaps make it a config.

**Comment by sschuberth** [comment]
> The only way searchcode can determine the owner is if it is a git or svn repository.

Well, Gerrit *can* only host git, so that shouldn't be the issue.

**Comment by boyter** [comment]
@sschuberth Sorry perhaps I misunderstood.

When you add the repository you want to to search if you select git it will clone a copy and the use that to determine the owner. If you select File repository it will leave the files in place and use Unknown for the user.

**Comment by boyter** [comment]
@ttgirod It will still be a git repository, just that its location happens to be on disk. As such you will see the owner calculated and not set to Unknown.

The way the git one works is to clone from the location. So long as it can clone then it will work as expected. Incidentally this allows you to use .ssh keys to pull so long as they are in the correct locations relative to the user running searchcode server.

**Comment by ttgirod** [comment]
OK, I spotted it, I think. The problem occurs if you happen to name the repository as "REPO:xxx", which was exactly our case, since we wanted to address multiple branch indexing within a single repository.
It looks like if you name a SearchCode repository as "REPO:branch", the code owner will always be classified as "Unknown". Whereas "REPO_branch" syntax works fine and the code owner gets displayed correctly.

It would actually be good to have some more convenient way to accommodate repository + branches name space. At the moment SearchCode does not allow you to create multiple repositories with the same name even if different branches are specified in the "branch" field.

**Comment by boyter** [comment]
Thats odd. Are you using the native git integration or are you setting it to use a git binary?

I will have a look into that because it should work in either case, but if the binary I can see that it may have a path issue.

Having better support for branches is one of those things I have in the TODO pile. I would like to allow adding a repository and then it would be inspected for all branches and you could then pick which ones to index. I need to have a think about the implications that has for adding via API and the like.

It may mean I will do a hard break with the current way this is implemented to allow this.

**Comment by ttgirod** [comment]
> I suspect its because I missed the handling of the new location when it has the / finds nothing and returns Unknown as a default. Something I can fix then.

Would be great, thanks. It's quite essential from our point of view, as Gerrit has hierarchical repository tree structure, and most of our repositories are named as "parentrepo/repo1/repo2".

**Comment by boyter** [comment]
Yep its literally just a bug. I just need to track it down and fix it. The fact I have people such as yourself reporting back helps a lot with me getting to the point I can push a new release.

**Comment by boyter** [comment]
@ttgirod Thanks for tracking that down. Was able to replicate and resolve. The latest commit should resolve that.

**Comment by boyter** [comment]
Have investigated SVN and it appears to be working as expected. While I was investigating I was able to resolve the non matching "By File Count" vs "By Line Count" issue on the repository overview pages which was a nice bonus.

Going to run this through the usual tests then probably close it out. I will also create a one off build and promote it to http://demo.searchcodeserver.com/ and use that as a long term run-in for this. Suggestions for a repository to index there with a / in the name appreciated (its a small server so nothing too large please :) _

**Comment by sschuberth** [comment]
@boyter, how about indexing these for demo purposes:

https://gerrit-review.googlesource.com/admin/repos/plugins/scripting/groovy-provider
https://gerrit-review.googlesource.com/admin/repos/plugins/scripting/scala-provider

These are plugins for Gerrit, so they're reasonably small, and I like the fact to use something that is hosted at the Gerrit instance which also hosts the Gerrit source code itself.

**Comment by boyter** [comment]
Sounds good. Ill use those then.

**Comment by ttgirod** [comment]
> @ttgirod Thanks for tracking that down. Was able to replicate and resolve. The latest commit should resolve that

Yes, that seems to have fixed it, thanks a lot!
By the way, our tests show that "REPO:BRANCH" syntax, i.e. repositories containing ":" in their names are also handled correctly now and the code owners are displayed right there. Could you please confirm whether this was indeed a part of your fix?

**Comment by ttgirod** [comment]
There is one more (albeit cosmetic) issue with the repositories browsing in SearchCode GUI:
in the repository overview `<URL>/repository/overview/PROJECTNAME/` there is a repository URL next to the word "Repository", where the repository location is used as the URL text (e.g. `file:///gerrit/gerrit06/git/test-projects/test-1.git`) and the repository source is used as the URL reference (e.g. `https://gerrit/projects/test-projects/test-10`). 
This seems to be a bit misleading as for the end users the way a repository is being accessed and indexed should be transparent. And hence, the information like the repository location URL (e.g. "file:///") should be available for the SearchCode admins only. So, I'd perhaps suggest not to mention it at all in the repository overview page.
On the other hand the information about the configured repository branch would be useful to display in the repository overview.

**Comment by boyter** [comment]
Yes it was. In theory you can now have any character in the repository name.

Yes I can see that being a bit annoying. There are times where you may not want to expose the repository. I will take that onboard when I start to refactor the add repository design in the future.

**Comment by sschuberth** [comment]
@ttgirod mind filing a separate issue about this so it does not fall through the cracks?

**Comment by boyter** [comment]
http://demo.searchcodeserver.com/?q=scala%20OR%20groovy

http://demo.searchcodeserver.com/repository/overview/plugins%2Fscripting%2Fscala-provider/
http://demo.searchcodeserver.com/repository/overview/plugins%2Fscripting%2Fgroovy-provider/

Added the suggested repositories to the demo site. Its still indexing (my poor tiny server!) but those are done and working.

**Comment by boyter** [comment]
Have been testing this for a while and it looks pretty clean. Only issue I have noticed is that I am getting stuck indexing but I belive this is down to the demo server having only a small amount of memory for the amount of code it is indexing. Going to close this down.
