### ISSUE TITLE
Index numeric results

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#124]
In my case, all tests have numeric id, in example 1.2.3.20, so if test fails I would love to be able search against this number, but "1.2.3.20" not 1.2.3.20 yields no results.

**Comment by boyter** [comment]
This should be pretty easy to do actually. If you want to do it yourself just modify the following code,

https://github.com/boyter/searchcode-server/blob/dfa20056b3a70c8de79ebd43856d454d49115811/src/main/java/com/searchcode/app/util/SearchcodeLib.java#L101

Which is there to pull out specific cases like this.

What I will do is add another database which can be extended to support additional interesting cases. This will allow anyone to extend it to their own situation.

**Comment by quasarea** [comment]
Works great, thanks!
