### ISSUE TITLE
Feature Enhancement: Link to repo on main overview page

### ISSUE THREAD

**Issue by NathanaelA** [boyter/searchcode-server#126]
Is there some way we can make a link on the overview page. http://server/repository/overview/SOMEREPO/ 

It would be really cool if maybe the title "Repository overview for SOMEREPO" is SOMEREPO was actually linked to the repo, so you could click through to the actual repo.

**Comment by boyter** [comment]
Sorry whereabouts did you want to see this? The repository overview page should already have this link. 

http://server/repository/list/

Or did you mean you want to see the overview on the main page

http://server/

Or somewhere else?

**Comment by NathanaelA** [comment]
For some reason I can not upload an image at all, at this point.   So I am trying to do this via text.  LOL...

http://demo.searchcodeserver.com/repository/overview/memcached/ on this page it lists the git repo; which is great if you are going to copy it to clone it.   So I think that should be left alone.    

But it would be nice if the title `Repository Overview for memcached` if maybe the `memcached` was a link to ` https://github.com/memcached/memcached` so that you can easily click through to the repo from this page.     Either that or add a link somewhere else in the page.   I love things being cross-linked so that it is easy to get from place a to place b.   

Does that make sense?

**Comment by boyter** [comment]
Ah gotcha. Actually you just found a bug. This should already be enabled if you add a link in the "Repository Source" when adding a repository. For some reason it is not appearing.
