### ISSUE TITLE
Feature Enhancement: Detailed information for overview file breakdown.

### ISSUE THREAD

**Issue by NathanaelA** [boyter/searchcode-server#127]
For example one repo that I'm looking at looks like:
```
6 Languages	
Markdown 2 files 23% of project
TypeScript 2 files 23% of project
Unknown 2 files 23% of project
JSON 1 files 12% of project
Javascript 1 files 12% of project
git-ignore 1 files 12% of project
```

I would love to be able to click on any of those and see the files they are, and if possible the file names that show up are clickable to actually view the source.

**Comment by boyter** [comment]
Sounds reasonable. It ties in somewhat with  #89 requires a few changes on the a backend to support it at this point though.

**Comment by boyter** [comment]
So sitting in master. I have some code that allows this to happen. What it does is piggybacks of the literal search option and links to a search that displays the above. 

Its not integrated into the same page however. Still thinking about if that should be the case.

<img width="644" alt="screen shot 2017-09-07 at 8 34 50 am" src="https://user-images.githubusercontent.com/612151/30137606-73682738-93a7-11e7-93a2-000d2f66ca0e.png">

<img width="986" alt="screen shot 2017-09-07 at 8 35 40 am" src="https://user-images.githubusercontent.com/612151/30137637-93d7ce10-93a7-11e7-9bab-9420a394545d.png">

**Comment by NathanaelA** [comment]
@boyter - Ben, this would be awsome.  It doesn't have to be the same page;  it is perfectly fine to reuse the rest of the system to keep it consistent.  :-D

**Comment by boyter** [comment]
Well it was more about me being lazy because its easier to implement :)
