### ISSUE TITLE
Feature Request / Question: Theming

### ISSUE THREAD

**Issue by NathanaelA** [boyter/searchcode-server#128]
I am looking to re-theme searchcode to go along with several other sites that are all a part of an integrated whole.  (So they will all be cross linked to each-other)

Is there an easy way to retheme the files without having to build a custom version of searchcode. 
I prefer to leave things as stock as I can; but it appears the freemarker templates are built into the app.

**Comment by boyter** [comment]
I am still investigating this #107 

I can add the ability to have a custom place for most things but the templates are indeed built into the application. I need to investigate if spark framework allows for the overloading of this.

**Comment by NathanaelA** [comment]
Thanks, it is then a duplicate of #107; for some reason I totally missed that one.   :-D
