### ISSUE TITLE
Multiple indexes

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#129]
Just an idea, but in my case I have static collection of 20 repositories and other 60 repos that are using different branches in different cases. I wonder how tricky it would be to be separate index process from UI and allowing UI to tap to more than one index. 

So I would end up with multiple indexers working with their set of repos and UI that can query against content provided by multiple of them.

It would also help with reindexing I guess, as I could run second indexing service to prepare new indexes, and when its done just update UI configuration, while up to now I have to run second application in local mode, then when its ready stop them and swap their configs. this change would introduce no downtime requirement

**Comment by boyter** [comment]
Actually looking at doing this in the next release 1.3.11 I should probably update the project board to reflect the current plan.

In short I wanted to have the ability to reindex everything and swap the indexes under the hood. Part of the planned fixes that will be going in.

**Comment by boyter** [comment]
Most of this is inside the branch newindex. Still need to run it it though a battery of tests before marking this as done though.

**Comment by boyter** [comment]
This is sitting in master branch now. Need to observe it in test for a long time before this gets marked as done. The main thing I am worried about is the background running tasks suspending and terminating when requested by the index. However you can now reindex everything without causing any downtime.
