### ISSUE TITLE
Issue with Symlinks

### ISSUE THREAD

**Issue by boyter** [boyter/searchcode-server#14]
There appears to be some sort of path traversal issue with looking at paths with symbolic links. Need to investigate why and resolve.

**Comment by boyter** [comment]
Symlinks appear to work correctly on OSX. The reported issue was with RedHat and CentOS. Will need to spin up some VM's and try this out.

**Comment by Ruzzz** [comment]
https://github.com/Ruzzz/searchcode-server/commit/480759c7e94c213168b4b4ad8027a5befb666a22

**Comment by boyter** [comment]
Resolved thanks to @Ruzzz
