### ISSUE TITLE
repository name issue

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#143]
Hi, just finally catch up with my stuff.

Have freshly build searchcode from sources.

Have some other issues, so in order to validate them before bothering you, I decided to start from scratch.

Repo name: **location1-applicationbuild-intel_nt4x6** causes the issue in console when opening it home page (this repo stats page):
```
Sep 11, 2017 2:22:57 PM java.util.logging.LogManager$RootLogger log
SEVERE: CodeSearcher getProjectStats caught a class org.apache.lucene.queryparser.classic.ParseException
 with message: Cannot parse 'reponame:': Encountered "<EOF>" at line 1, column 9.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
```
Double checked in db that there is no space or whatever in it.

Cheers

**Comment by boyter** [comment]
Odd I am not seeing this. Do you mean when you have added a repository with the name "location1-applicationbuild-intel_nt4x6" and then you try to browse to the repository overview page or search that it does not work?

I have included what I see below using the same name. The above issue should onl

<img width="1109" alt="screen shot 2017-09-12 at 8 02 03 am" src="https://user-images.githubusercontent.com/612151/30298963-d1fb8852-9790-11e7-9d36-424b0c2e4e64.png">
<img width="1194" alt="screen shot 2017-09-12 at 8 02 21 am" src="https://user-images.githubusercontent.com/612151/30298964-d20839da-9790-11e7-9eab-a4d3dd1285ad.png">

I can replicate the issue if I prefix location1-applicationbuild-intel_nt4x6 with a space which results in the below and the above error that you indicated however. Perhaps this is what you did?

<img width="1042" alt="screen shot 2017-09-12 at 8 05 31 am" src="https://user-images.githubusercontent.com/612151/30299034-38d1cfdc-9791-11e7-84ab-29a888fd38ac.png">

**Comment by boyter** [comment]
TODO - Resolve the above. Probably need to use the literal search field for the above using the conversion as it should be more reliable.

**Comment by quasarea** [comment]
It happens on opening repository details from repositories page http://localhost:8080/repository/list/ . 
`SEVERE: CodeSearcher getProjectStats caught a class org.apache.lucene.queryparser.classic.ParseException with message: Cannot parse 'reponame:': Encountered "<EOF>" at line 1, column 9.`

Could it be that its validating repository name along with "reponame:" prefix of some sort? 

You are doing something like that in :
\searchcode\app\service\route\CodeRouteService.java, 337:
\searchcode\app\service\route\SearchRouteService.java, 70
```
List<String> reposList = Arrays.asList(repos).stream()
                            .map((s) -> "reponame:" + QueryParser.escape(s.replace(" ", "_")))
                            .collect(Collectors.toList());
```

**Comment by boyter** [comment]
Yep I am in the middle of changing that over to use the method that should be shared by all methods.

**Comment by boyter** [comment]
Should be resolved. Could you please try it out and let me know?

**Comment by quasarea** [comment]
Unfortunately not, but you managed to alternate it a bit :) - its now "rn:" instead of "reponame:"
```
SEVERE: CodeSearcher getProjectStats caught a class org.apache.lucene.queryparser.classic.ParseException
 with message: Cannot parse 'rn:': Encountered "<EOF>" at line 1, column 3.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
```

**Comment by boyter** [comment]
So is this actually resulting in an issue thats visible anywhere on the page? IE you cannot see the project results page? Or is it just the above in the logs?

**Comment by quasarea** [comment]
its log only, will confirm & close tomorrow

**Comment by boyter** [comment]
Just following up. This look like it is resolved for you?

**Comment by boyter** [comment]
Ah the ultimate issue was down to me not understanding orElse vs orElseGet in Java Optionals. To be fair the Else suggests that its a control flow statement. Fixed in bab791042aa51580a5f029721aaef7ad5072984e

**Comment by quasarea** [comment]
tried to build just now, but got test errors, see #148

**Comment by boyter** [comment]
Resolved so should be able to try it out again.

**Comment by quasarea** [comment]
Confirmed, it is now fixed, thanks
