### ISSUE TITLE
Question: Ability to detect binary?

### ISSUE THREAD

**Issue by NathanaelA** [boyter/searchcode-server#147]
I have my server read the readme, and license (i.e. no extension files).     But frequently it is picking up a binary file that has no extension.   Is their a way to make it a bit smarter in detecting binary files; or some way I can maybe manually blacklist a specific file name

**Comment by boyter** [comment]
So the guessing of a binary file is a hard one. The way it works is that it scans the top of the file and counts how many of the characters are ASCII. If less than 30% are ASCII the assumption is made that it is a binary file. Note that this check only occurs if binary_guess is set to true in the properties file.

I have made a small change that will pick up the full extension in the black list. So you can in this case blacklist exact files. To do so add the value to the properties file value,

binary_extension_black_list=license,readme.ignore

at which point any file that matches that license or *.license or readme.ignore will be ignored. This is sitting in master so you would need to build from the latest source to get it right now though sorry.

One thing to note, the whitelist take priority over the blacklist.
