### ISSUE TITLE
fab build_release modifies source files

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#159]
Every time I build sources with `fab build_release` this three files get modified (so I have to undo changes in order to pull again):
* `src/main/java/com/searchcode/app/App.java` 
  `public static final boolean ISCOMMUNITY = false; `

* `src/main/resources/spark/template/freemarker/search_ajax.ftl`  from 
```
<script src="/js/mithril.min.js"></script><script src="/js/underscore-min.js"></script>
<script src="/js/chart.js"></script><script src="/js/cache.js"></script><script src="/js/script.js">/script>
```
  to 
```
<script src="/js/script.min.js"></script>
```

* `src/main/resources/public/js/script.min.js` 
  being totally replaced/rebuilt

Maybe those files should not be delivered by source control if they are created/modified by build?

**Comment by boyter** [comment]
So it is there for a reason. It saves me having to remember to do the ISCOMMUNITY boolean flip between the community and paid for release as well as compiling and minifying all the javascript. 100% this file is required.

Same story with the javascript. It modifies the template to switch between development and release mode. 100% the files are required to be checked in.

If its a huge problem you can run it like so ```fab build_release && fab configure_local``` which should restore it back for you.
