### ISSUE TITLE
Add special tokens such as 'repo:', 'file:', 'owner'

### ISSUE THREAD

**Issue by issmirnov** [boyter/searchcode-server#161]
It would be really cool to be able to leverage the searchbox for specifying filters on the fly. This would allow faster search and save on keystrokes and clicks. Some examples:

- `repo:` or `r:` - allows picking a repo. Would populate the `&repo=` url param
- `file:` or `f:` - populates the `&path=` URL param
- `lang:` or `l:` - populates `&lang=` URL param. 
- `owner:` or `o:` - specify owner, keyed by name or email. Ideally subset of name or email would work

The drawbacks is that if the code actually has a `repo:` it would not be caught. The user could just search for `repo` though, and that would still work.

HTH. This would be really cool to see.

**Comment by boyter** [comment]
Actually this is already there. For all of them. The only catch is that you need to use a literal search. There isn't actually a problem with turning this on for all searches though. To do so you would need to click the "literal search" checkmark on the "search options" section in the bottom of the filter options portion of the search.

To use it see the below (also included on the documentation page)

fn
File name. E.G. fn:search*

rn
Repository name. E.G. rn:searchcode*

ln
Language name. E.G. ln:java OR ln:bourne_again_shell

on
Owner name. E.G. on:ben

fl
File location. E.G. fl:src*

**Comment by issmirnov** [comment]
Ooh, that's dope! Would it be possible to have these live in the config, so I could change `on` to `own`, for example?

**Comment by boyter** [comment]
Not currently. They are actually the values used in the Lucene index itself. I guess I could make that customisable but not sure if thats the best idea.

I could add a mapper which looks for ones that can be replaced. Might work better that way but is a bit of parsing nightmare.

**Comment by issmirnov** [comment]
Any feature request that has the word "nightmare" in it can wait. Thanks - stoked to use the existing tokens!.Was able to scan my codebase for anti-patterns just now, falling in love with this tool!

**Comment by boyter** [comment]
Glad you like it! Let me know if you do run into serious bugs and I hope you enjoy the next few releases, some of them should be epic!

**Comment by sschuberth** [comment]
For the record, I cannot get this to work. E.g.

http://demo.searchcodeserver.com/?q=word&lit=true

shows matches, but

http://demo.searchcodeserver.com/?q=word%20fn%3Ahunspell.h&lit=true

does not seem to filter them down to matches in files called "hunspell.h".

**Comment by boyter** [comment]
I really do need revisit how this works. Whats happened is that hunspell.h is popped to the top of the search results, but what you would expect is that it would apply an AND between the words and you would only get a single result.

I am likely to take this onboard when I start working on the next release which is likely going to be a major one with breaking changes. Actually there will likely be one more minor release before then.

**Comment by sschuberth** [comment]
Unfortunately, I also cannot work around that by adding an explicit "AND":

http://demo.searchcodeserver.com/?q=word%20AND%20fn%3Ahunspell.h&lit=true

This now shows no matches at all.
