### ISSUE TITLE
Adding repos through API fails on indexing step

### ISSUE THREAD

**Issue by issmirnov** [boyter/searchcode-server#163]
Hi,

I'm playing with the API, setting up a small script to populate all of my repos. I'm using [signed requests](https://searchcodeserver.com/knowledge-base/details-of-searchcode-server-api.html), sending URL's in the form of:

```

# generate vars
repourl = "https://github.com/issmirnov/dotfiles"
reponame = repourl.split("/")[-1].rstrip()
repotype = "git"
repousername = test
repopassword = test
reposource = repourl
repobranch = "master"


message = "pub=%s&reponame=%s&repourl=%s&repotype=%s&repousername=%s&repopassword=%s&reposource=%s&repobranch=%s" % (
      urllib.quote_plus(publickey),
      urllib.quote_plus(reponame),
      urllib.quote_plus(repourl),
      urllib.quote_plus(repotype),
      urllib.quote_plus(repousername),
      urllib.quote_plus(repopassword),
      urllib.quote_plus(reposource),
      urllib.quote_plus(repobranch)
    )
sig = hmac(privatekey, message, sha512).hexdigest()
 
url = "%s/api/repo/add/?sig=%s&%s&hmac=sha512" % (base_url, urllib.quote_plus(sig), message)
```

Calling this URL returns `added repository successfully`, but when I check the `repository/list/` I see that the file count for the repo is 0. I tested this by adding the exact same repo (same url, username/pass) using the `/admin/repo/` interface and the indexer instantly found all 3 test files.

It seems that while the repo is added, some information is lost when using the API. For reference, the username/password I was using is `test`/`test`, so I don't think it's any ASCII decoding issues.

Extract from logs:
```
INFO: Thu Oct 26 20:21:55 PDT 2017: QuartzScheduler_Worker-40 49: Update found indexing https://github.com/issmirnov/dotfiles

WARNING: Thu Oct 26 20:21:55 PDT 2017: QuartzScheduler_Worker-40 49: ERROR - caught a class org.eclipse.jgit.api.errors.InvalidRemoteException in class com.searchcode.app.jobs.repository.IndexGitRepoJob updateGitRepository for dotfiles
 with message: Invalid remote: origin
```

**Comment by issmirnov** [comment]
Looking at api logs (`/admin/logs/?level=API`) I see `Valid signed repoAdd API call using publicKey=APIK-XXXXX`, so seems we are getting at least to [here](https://github.com/boyter/searchcode-server/blob/699e6e556db88acf206bc84938581382673b6dc0/src/main/java/com/searchcode/app/service/route/ApiRouteService.java#L359)

**Comment by boyter** [comment]
Odd thats certainly one of the things that I run through batteries of tests. Are you building from master or using the community release?

**Comment by issmirnov** [comment]
Using the latest release (v1.3.11). Running on Ubuntu 16.04, using `/usr/lib/jvm/java-8-oracle/` for my JAVA_HOME. 

I can send you my test account credentials + live repo URL via email, if you want to try to repro?

**Comment by boyter** [comment]
No thats fine.

Although "https://github.com/issmirnov/dotfiles" if you are using that it will probably not work. It should be "https://github.com/issmirnov/dotfiles.git" if I am not mistaken.

**Comment by issmirnov** [comment]
I figure it out. PEBKAC on my part.

I'm writing a script that parses a list of URL's and generates the curl command for me. Turns out when I use `with open(repo_list) as f:` + `for repourl in f:`, there's a newline terminator. I had `rstrip()` on the repo name, but didn't realize that the `repourl` and `reposource` still had it. I was able to check this by grepping for `%0A` in the request URL and seeing it appear on the trailing end of those two params.

Adding an `rstrip()` on the `repourl` immediately after reading the line fixes is.

FWIW, if it's a trivial fix to trim newlines from all params this would likely save some future users the pain. I'll post my finalized script when it's ready.

**Comment by issmirnov** [comment]
Final script below. Note that users will need to put in proper values for `base_url`, `publickey`, `privatekey` and put the list of repos into a file called `repo_url`. I was able to put in repos without the `.git` suffix in the URL and it worked fine.


```
#!/usr/bin/env python
# Script for populating repos in searchcodeserver. Prompts for username/password, then reads list of repos
# calls the API. 
# Contributor: Ivan Smirnov, isgsmirnov@gmail.com.
# Attribution: This is a wrapper for the code at https://searchcodeserver.com/knowledge-base/details-of-searchcode-server-api.html, full credit to Ben Boyter.

from hashlib import sha512
from hmac import new as hmac
import urllib2
import json
import urllib
import pprint
 
# config
base_url = "http://server.here"
publickey = "APIK-XXXXXX"
privatekey = "XXXXXXXX"
repo_list = "./repo_list"
 
# Generates URL to add repo to api.
def gen_post_url(repourl, username, password):
    reponame = repourl.split("/")[-1]
    repotype = "git"
    repousername = username
    repopassword = password
    reposource = repourl
    repobranch = "master"
 
    message = "pub=%s&reponame=%s&repourl=%s&repotype=%s&repousername=%s&repopassword=%s&reposource=%s&repobranch=%s" % (
      urllib.quote_plus(publickey),
      urllib.quote_plus(reponame),
      urllib.quote_plus(repourl),
      urllib.quote_plus(repotype),
      urllib.quote_plus(repousername),
      urllib.quote_plus(repopassword),
      urllib.quote_plus(reposource),
      urllib.quote_plus(repobranch)
    )
 
    sig = hmac(privatekey, message, sha512).hexdigest()
    url = "%s/api/repo/add/?sig=%s&%s&hmac=sha512" % (base_url, urllib.quote_plus(sig), message)
    return url
 
def add_repo(url):
    data = urllib2.urlopen(url)
    data = data.read()
    data = json.loads(data)
    print "Success: %s, details: %s" % (data['sucessful'], data['message'])
 
if __name__ == "__main__":
    username = raw_input("Enter username: ")
    password = raw_input("Password: ")
    with open(repo_list) as fp:  
        for repourl in fp:
            url = gen_post_url(repourl.rstrip(), username, password)
            add_repo(url)

```

**Comment by boyter** [comment]
I was hoping it was PEBKAC as that would be a pretty serious bug otherwise. Adding a trim probably wouldn't be too hard actually. Might make a validator as part of the source file though which should result in invalid ones being rejected too.

**Comment by issmirnov** [comment]
Sounds good. Do you want to keep this open for the feature request on param validation/trimming, or close this out?

**Comment by boyter** [comment]
Going to close it out. Have created #164 to create a better way to highlight the failures.
