### ISSUE TITLE
2018 release ETA?

### ISSUE THREAD

**Issue by issmirnov** [boyter/searchcode-server#169]
Hi,

I've noticed a ton of commits and closed issues - looks fantastic. Any word on a new release for 2018? I see that master is marked unstable.

Thanks for the amazing work!

**Comment by boyter** [comment]
Probably in the next week or so from when I post this message. I need to run through a burn in test to ensure that everything works as expected. Its looking fine at the moment though so I do not anticipate there to be too many issues with it.

Cheers.

**Comment by issmirnov** [comment]
Fantastic, thanks!!

**Comment by issmirnov** [comment]
Woohoo! Thank you for the fresh release.

**Comment by boyter** [comment]
No problem. Took a little bit longer than expected as I ran into a few small bugs that needed to be resolved.

**Comment by issmirnov** [comment]
Thanks for the great work. Upgraded without a hitch, everything looks perfect.

**Comment by boyter** [comment]
Great to hear!
