### ISSUE TITLE
Add the ability to change the URL context 

### ISSUE THREAD

**Issue by klandon** [boyter/searchcode-server#176]
Currently it seems to be no way to change the url context to run on anything other than "/"

Would be nice in the config if we can set a param such as "URL_CONTEXT=/searchsomecode/", so that the url would be something like "http://hostname:8080/searchsomecode/" and that would be the bases of the application.

**Comment by boyter** [comment]
Forgive me for asking but whats the reason behind doing something like this though? Are you trying to host multi tennent applications or some such?

I think it would be reasonably hard due to the way SparkJava works but if there is a really good reason for it I can look into it further.

**Comment by klandon** [comment]
First thanks for the consideration.

Example in my case is I have a single entry point for our engineers lets call it "engineering.mycomp.com" from that entry point we use URL routing to direct them to certain services such as "engineering.mycomp.com/searchwiki" might go to codelibs Fess for searching wikis and "engineering.mycomp.com/searchcode" would go to searchcode server for searching our git repos. We currently use NGINX to handle the url routing from the entry point but the setup is complex in handling all of the routing and re-writing of urls when we cant use a simple proxy pass with a accurate context.

I completely agree with the complexity of spark java hence why I am asking here :) for I am no expert in spark java and attempted this myself but failed. I think it is a nice to have but otherwise my case may be an edge case and there are other ways to resolve but thought i would at least ask.

**Comment by boyter** [comment]
So I had a play around with this and failed to get it to play nicely. To be honest the nginx config is what I would have done as well. I can understand why you would want to make it simpler though.

Usually my recommendation is to put searchcode on another subdomain when you have that situation, so say ```searchcode.mycompy.com``` which usually works out pretty well.

Sorry about that. I wish I could accommodate you on this one.

One thing to keep in mind is that you do need to set the host-name for RSS feeds and the like in the properties file like the below in order for those to be considered valid.

```host_name=localhost:8080/searchcode/```

**Comment by klandon** [comment]
much appreciated thanks for trying.

**Comment by boyter** [comment]
Sorry it couldn't be done for you. Thanks for understanding though.
