### ISSUE TITLE
Issues with searching for identifiers in C++ namespaces

### ISSUE THREAD

**Issue by sschuberth** [boyter/searchcode-server#188]
On your internal searchcode instance we're having trouble searching for C++ identifiers that include a namespace, they are not found. To compare, I tried to search for "std::cout" on the public instance, which returns some results:

https://searchcode.com/?q=std%3A%3Acout

But interestingly, e.g. a search for "std::vector" returns a 500 error on the first try:

https://searchcode.com/?q=std%3A%3Avector

![image](https://user-images.githubusercontent.com/349154/42203465-205e859e-7e9f-11e8-9c8d-9c3658b97379.png)

I seems to make a difference whether you directly click the above search URL for the first time, or whether you enter "std::vector" at https://searchcode.com/ and then click "search". The latter seems to work. Very odd...

**Comment by boyter** [comment]
Actually the public instance is a separate codebase entirely compared to the local one searchcode server. I do have a public searchcode server instance at http://demo.searchcodeserver.com/ however it is only running over about 20 repositories. I am in the process of merging the codebases though and hopefully at some point in the next few months they will be running 90% the same code.

Can you provide a list of terms you are searching for and files that you belive should match. I can then improve the index pipeline to take these into account.

**Comment by sschuberth** [comment]
Sure. As one example, I'd expect http://demo.searchcodeserver.com/?q=PhysicsServer%3A%3Aget_singleton to match the 16 instances of "PhysicsServer::get_singleton" in https://github.com/godotengine/godot/blob/master/scene/3d/area.cpp.

**Comment by boyter** [comment]
Cheers. Ill look into that now.

**Comment by boyter** [comment]
![image](https://user-images.githubusercontent.com/612151/42264424-e8333c80-7fb3-11e8-8fcc-9f31e485046b.png)

Should be resolved with 964616a597354c450cee3cf78677b07880520c9b

**Comment by sschuberth** [comment]
Great, thanks for the quick fix! When will this get deployed to demo.searchcodeserver.com for some further testing?

**Comment by boyter** [comment]
Probably in the next day or two. I want to do some more local testing before I actually publish it.

**Comment by boyter** [comment]
Long time coming but published to demo.searchcodeserver.com for further testing.

**Comment by sschuberth** [comment]
Hmm, thanks, but is the change really live yet? http://demo.searchcodeserver.com/?q=PhysicsServer%3A%3Aget_singleton from my comment above still returns no matches...

**Comment by sschuberth** [comment]
Ah, sorry for not looking at the indexing status myself. Thanks!

**Comment by sschuberth** [comment]
But wait, is seems https://github.com/godotengine/godot/ is gone from the list?

**Comment by boyter** [comment]
Yes it is for the moment. I will be adding it back soonish.

**Comment by boyter** [comment]
http://demo.searchcodeserver.com/?q=PhysicsServer%3A%3Aget_singleton

appears to work as expected now.

**Comment by sschuberth** [comment]
Indeed, great, thanks!
