### ISSUE TITLE
Add server side syntax highlighting

### ISSUE THREAD

**Issue by boyter** [boyter/searchcode-server#190]
This is a requirement for searchcode.com 

Need to have server side syntax highlighting, possibly using Pygments through Jython.

NB last time I tried this it was terribly slow.

**Comment by boyter** [comment]
Pygments through Jython appears to still be too slow to be usable. It takes multiple 10's of seconds to cope with some files.

Perhaps contact the Pygements team about this. But otherwise I think the better option would be to call out to another process such as Chroma https://github.com/alecthomas/chroma and mark things up that way, depending on how fast it is.

**Comment by issmirnov** [comment]
How does [prism.js](https://prismjs.com/) compare? If you are open to adding logic in the frontend this might be an interesting option.

**Comment by boyter** [comment]
Looks better. Might give that a whirl. 

Server side just seems like not an option in the java world, unless you call out to an external process or something. Annoying.

**Comment by issmirnov** [comment]
Yeah, IPC is always a pain, especially when trying to send out neat bundles...

**Comment by boyter** [comment]
That's for dammed sure. I think I looked at prism.js before and had some issues with getting it to have linkable line numbers. Might be better this time around though.

**Comment by boyter** [comment]
Prism does seem to have a lot of rendering issues. Which is rather annoying because it is quite nice. 
![image](https://user-images.githubusercontent.com/612151/43125774-4e1e22ca-8f6e-11e8-9d54-d27e853408cb.png)

**Comment by boyter** [comment]
Could just be a clash of CSS however.

**Comment by boyter** [comment]
Was a CSS clash. This might be possible to do server side using Chroma and Nashorn as it was designed to work on the server as well.

```
var Prism = require('prismjs');

// The code snippet you want to highlight, as a string
var code = "var data = 1;";

// Returns a highlighted HTML string
var html = Prism.highlight(code, Prism.languages.javascript, 'javascript');
```

Should be reasonably easy to get running in Java.

**Comment by boyter** [comment]
End the end went with a simple Go server that uses Chroma to achieve this. https://github.com/boyter/searchcode-server-highlighter
