### ISSUE TITLE
Feature Request: Print Version Info in Footer

### ISSUE THREAD

**Issue by issmirnov** [boyter/searchcode-server#193]
I recently set up an Ansible role to auto update to the latest release. There is currently no way to view the version of the server through the web UI, so it's hard to verify that the upgrade worked properly.

Could we get the version printed in the footer, or perhaps some well known API endpoint?

Thanks!

**Comment by boyter** [comment]
API is probably a better idea. There is an internal endpoint used by the admin pages for this but a better one would be something available for anything to call.

**Comment by issmirnov** [comment]
Fantastic, thanks!

**Comment by issmirnov** [comment]
Tested on my role, it works great. Thank you!

**Comment by boyter** [comment]
Great to hear!
