### ISSUE TITLE
Add Boost repo to demo.searchcodeserver.com

### ISSUE THREAD

**Issue by sschuberth** [boyter/searchcode-server#194]
https://github.com/boostorg/boost is a "nice" complex C++ code base that would be a good test case for issues like described in #188. Additionally, it makes [heavy use of git submodules](https://github.com/boostorg/boost/tree/master/libs) about which I'm curious how searchcode is handling them currently:

* Does searchcode do a recursive clone when indexing, so that submodules in the state as used by the super-project are indexed, too?
* Or are submodules manually parsed and indexed as individual repos, applying any branch name restrictions etc.?
* Where are matches in submodules displayed, as a match in the super-project, or a match in the underlying Git repo?

**Comment by boyter** [comment]
Added.

So sub-modules. It will just do a naive git clone. However https://github.com/boyter/searchcode-server/issues/92 will allow you to modify how the the clone is done so it will be possible to do it however you wish.

The way searchcode works is that it will clone a repository then treat it as a single unit to search over. If its in the file system at that point its something to search.

Not that this cannot change in the future though.

**Comment by sschuberth** [comment]
> The way searchcode works is that it will clone a repository then treat it as a single unit to search over. If its in the file system at that point its something to search.

Good to know, thanks for spelling this out!

As the main point was to add Boost, I'll close this.
