### ISSUE TITLE
fuzzy search not working

### ISSUE THREAD

**Issue by tjhgit** [boyter/searchcode-server#199]
if I enter lightgbs~3 it does not do the fuzzy search. Instead it says try the search lightgbs 3. Also term boosting with ^ does not seem to work.

**Comment by boyter** [comment]
To support fuzzy search `lightgbs~3` you would need to first check "Literal Search" on the bottom of the filter bar. With this enabled searches go though directly to the index and should perform as you would expect.

Let me know how this works out for you.

**Comment by boyter** [comment]
Closing down due to no response.
