### ISSUE TITLE
Indexing tabular data

### ISSUE THREAD

**Issue by cakiki** [boyter/searchcode-server#249]
Hello! I'm working with data that's in parquet format (one row is one file from a repository). Is there any way to use `searchcode` to index data by somehow streaming row batches?

Every row is formatted like shown here: https://hf.co/datasets/bigcode/the-stack#data-fields

**Comment by boyter** [comment]
Sadly no. It treats everything as text. You would need to preprocess it to get the approach you want I am sorry to say.
