### ISSUE TITLE
Add better logic when cleaning repository names

### ISSUE THREAD

**Issue by boyter** [boyter/searchcode-server#29]
Repository names need to be valid filesystem characters. Should be enforced and let the user know when it is wrong.

**Comment by bskrtich** [comment]
I would like to add, it would be nice to be able to use any char in the name, so in the UI it would display that way but for file system operations it should just replace bad chars with like a underscore or something.

**Comment by boyter** [comment]
That's a better solution. I will implement as mentioned above.

**Comment by boyter** [comment]
Going to push this out to all release sooner which resolves many memory issues.

**Comment by boyter** [comment]
Going to change this back to enforcing names consisting of just alphanumeric characters and the - character. It makes things much simpler to reason about. There is some logic checking this now on the add page but still not enforced server side.

**Comment by boyter** [comment]
This is now enforced for all entrypoints adding repositories through the application.
