### ISSUE TITLE
No support for searching Chinese words

### ISSUE THREAD

**Issue by schubertzhang** [boyter/searchcode-server#45]
I had just buy a full version and try it, but not support searching for Chinaese words.

I think it should be easy to add this feature, do you have plan?

**Comment by boyter** [comment]
Hi,

Sorry about how long this took to reply to.

It certainly does work for displaying extended unicode characters such as those in Chinese.

Do you have an example that did not work for you? For example were you trying to search for 好 in 你好?

Or was it that a match for 你好 was not matching 你好?

I can then make the changes to resolve this.

Ben

**Comment by schubertzhang** [comment]
Thanks Boyter.

I think it may be a “Chinese words segmentation" issue, such as you can search “你好”, but searchcode indexer cannot support ”你“ and "好"  in "你好".

**Comment by boyter** [comment]
Yes the indexer by default is set to the standard lexer from memory.

I think it should be possible to add an option to select the Chinese one via the properties file. I will start implementing this on a branch and let you know here when I have something working.

Sorry about how long this too to respond, im currently overseas with limited access to internet.

**Comment by boyter** [comment]
I have a version of this sitting in a branch,

https://github.com/boyter/searchcode-server/tree/chinese

It us using the Smart Chinese Analyser 

https://mvnrepository.com/artifact/org.apache.lucene/lucene-analyzers-smartcn/5.5.0

In addition I allowed the selection of the analyser through the properties file. The default is still the suggested analyser but you can also now choose Chinese, Keyword and Standard in case someone wants stemming.

I still need to perform additional tests for this, but would you like to try out a beta version? If you like you can build from the branch or I can create a build for you to try out.

**Comment by boyter** [comment]
So one issue that has come up when using the Chinese Analyzer is that the search results are not as good as the custom one that searchcode server uses. I am looking into other ways to achieve the same result but with better code search results.

**Comment by boyter** [comment]
I have reverted the logic for the Analyzer and changed over to splitting the interesting characters. As such a search for "你" or "好" will now match "你好". I have merged this into master.

Would you be willing to try out a special build for this?

**Comment by boyter** [comment]
Hi just checking if you would be willing to try a special build for this one?

**Comment by boyter** [comment]
No response. Going to close this down.
