### ISSUE TITLE
mvn test in windows failed

### ISSUE THREAD

**Issue by waterbeach** [boyter/searchcode-server#46]
the screenshot show the error details,I run it in windows,and I change the path to the git executable for windows system in the searchcode.properties file, but it no use,Is there any way to solve it？
![image](https://cloud.githubusercontent.com/assets/11172280/21545973/98c8ff86-ce16-11e6-80a2-9e826f50c50b.png)

**Comment by boyter** [comment]
It should work for Windows, however you would need to change the path in the properties file to have unix style path separators, EG c:/git/git.exe

Oh its hardcoded in the tests... I should resolve this to use the properties file.

I will need to set this up on a Windows machine to confirm that it works. This will probably have to wait until around the 10th of January though as I have limited internet access till then.

You can probably ignore those end to end tests for the moment though. They aren't very well written and need to be refactored to ensure they work correctly every time. Sorry about that.

**Comment by waterbeach** [comment]
thx reply me.Shortly afterwards,I configured it successfully by changing the properties file.but There are still problems,it can relate only one repository on github,why is this?and occupy a lot of  memory....

**Comment by boyter** [comment]
You should be able to add as many repositories as you like so long as they all have unique names. For example if I wanted to index master and feature1 branches of a git repository I could add them using the  bulk uploader page using the following,

phindex,git,https://github.com/boyter/Phindex.git,,https://github.com/boyter/Phindex,master
phindex_feature1,git,https://github.com/boyter/Phindex.git,,https://github.com/boyter/Phindex,feature1

As for memory/RAM usage, searchcode server can run with 512mb of RAM without issue, but really it depends on how many files/repositories you are trying to index. How much RAM is it using in your case? If you are running the JAR you can pass in the -Xmx argument via command line to reduce the heap memory.

**Comment by boyter** [comment]
Updated to use the properties file for the git path now.

https://github.com/boyter/searchcode-server/commit/60ccd163a465842667acb759cc39c372f6b71c03

This will allow running of the tests more easily on Windows. 

Let me know if you have any issue with the above response about adding repositories and RAM usage, and if not I will close this issue.

**Comment by boyter** [comment]
Checking if you have answers to the above? If not I will close this task down soon.

**Comment by boyter** [comment]
No response. Going to close this down.
