### ISSUE TITLE
Publish Community release to DockerHub

### ISSUE THREAD

**Issue by boyter** [boyter/searchcode-server#47]
Publish Community release to DockerHub

**Comment by boyter** [comment]
https://github.com/boyter/searchcode-server/blob/master/assets/docker/Dockerfile

Updated to build and appears to work correctly. However need to wait for the new release to be published as the shell script https://github.com/boyter/searchcode-server/blob/master/searchcode-server.sh needs exec (since added) and this will make it into the new release.

**Comment by boyter** [comment]
Note this is not a production ready release as it won't use a mounted filesystem and the password is set to the default in the properties file, but it does make it painless to setup and run a test copy.

**Comment by bskrtich** [comment]
This looks to be a nice addition, I would recommend one change to your dockerfile. The base image you reference is deprecated and not updated any more since the end of the year. You should use 
openjdk:8-jre

For more info see https://hub.docker.com/_/java/

**Comment by boyter** [comment]
Sounds good. I am still getting into the world of Docker :) 

I will make the change and push it up to Dockerhub in a few days.

**Comment by boyter** [comment]
Uploaded.

https://hub.docker.com/r/searchcode/searchcode-server-community/

Need to add to the README.md
