### ISSUE TITLE
Refactor Admin Pages

### ISSUE THREAD

**Issue by boyter** [boyter/searchcode-server#53]
The admin pages are becoming a bit of a mess. Need to refactor them to present the data in a better way.

**Comment by boyter** [comment]
Add index status to repository overview page.

**Comment by quasarea** [comment]
#73 this could be part of this refactoring as well, at least in first instance

**Comment by boyter** [comment]
Not really part of the admin page though really, although it shares some of the improvements that have gone on over there.

**Comment by boyter** [comment]
Going to close this down. Auditing of the API keys would have been nice, but probably time to push this into a release.
