### ISSUE TITLE
Save stats to database

### ISSUE THREAD

**Issue by bskrtich** [boyter/searchcode-server#55]
It would be great if "Number of Searches" wasn't lost on restart. Of course if you do that we would also need a way to reset the count.

**Comment by boyter** [comment]
Related to https://github.com/boyter/searchcode-server/issues/53

Was looking at doing this as part of that work anyway, but going to leave this open.

**Comment by boyter** [comment]
Done. Sitting in the master branch. Will be released with version 1.3.8 at some point in the future.

**Comment by bskrtich** [comment]
Thank you!
