### ISSUE TITLE
when i finished "Add Repo", how can i know when the index process being finished, cause the number of searching results  is 0.

### ISSUE THREAD

**Issue by zhuzhujulie** [boyter/searchcode-server#61]

**Comment by boyter** [comment]
This is something that needs to be worked on.

https://github.com/boyter/searchcode-server/issues/53

Currently you can go to location on disk where the repository is, so if you are using the default and the project name is test,

./repo/test/

And look for the following directory,

searchcode.index.success

If that directory exists then searchcode believes that it has indexed all files in the repository.

I am going to expose the result of these inside the repository page while working on admin to resolve this issue.

**Comment by boyter** [comment]
One other thing to consider is enabling the option

```log_indexed=true```

Inside the searchcode.properties file. This will dump a log file to the ./logs/ directory (by default if not changed) which will be the name of the repository csv. This can be analysed to determine why something is being indexed or not.

Lastly you can check the log's. If you have only enabled severe or warning logs (the default) then login to the admin page and view the logs page. You can then view the info logs which should help diagnose the issue.

**Comment by boyter** [comment]
Have added two visual indicators in the admin page to help with this. The first being a running index jobs display that is polled every 3 seconds and displays the running jobs. The second is a visual indicator next to the repository in the admin page which will show "Indexed ✓" if the index is finished.

Will look into adding a better realtime page which shows expected times for jobs at a later date.
