### ISSUE TITLE
Publish hash of seachcode download

### ISSUE THREAD

**Issue by bskrtich** [boyter/searchcode-server#64]
It would be great that when you publish a new version that you also publish of at least a sha256 hash of the download. This way we can check the validity of the file after download. I do this for the setup of a docker image using seachcode.

**Comment by boyter** [comment]
Going to mark this as a bug as it is something that 100% should be done.

**Comment by boyter** [comment]
Done. See Current release 1.3.x change-log on the following page https://searchcode.com/product/

**Comment by bskrtich** [comment]
Cool! Can you also publish these hashes in their own files for automatic checks?

**Comment by boyter** [comment]
Sorry but what do you mean by this?
