### ISSUE TITLE
On the homepage of searchcode, i saw many alternative items, such as search using characters or filter by source etc? SO is there a user manual for us to understand how to use searchcode to search with these items? I can't find it, Thanks.

### ISSUE THREAD

**Issue by zhuzhujulie** [boyter/searchcode-server#68]

**Comment by boyter** [comment]
There isn't currently.

When I end up moving searchcode.com over to use the searchcode-server codebase then there will be as it should in theory be easier to maintain. For the moment though the examples are the best there is sorry.
