### ISSUE TITLE
Luke optimisations makes index not readable for searchcode

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#70]
Hi, tried to optimize index using recent luke-6.4.1 from https://github.com/DmitryKey/luke/releases

Tried both with Compound and Standard file format. Each resulted with SearchCode showing 0 elements in index.

Index is still browsable/searchable by luke itself

**Comment by boyter** [comment]
I was never able to get it working myself, but I only tried for a few minutes. The lucene version used is 5.5.0 so Luke should be able to read from it.

Perhaps try an older version of luke and see if that resolves the issue?

**Comment by quasarea** [comment]
I will try with other versions of luke and maybe manage to catch something in logs as well

**Comment by boyter** [comment]
Let me know the results, but is a plain jane version of Lucene so there is no reason that Luke should not be able to read it.

**Comment by quasarea** [comment]
Using https://github.com/DmitryKey/luke/releases/tag/luke-5.5.0 allows me to reindex and still being usable in searchcode, problems begin from https://github.com/DmitryKey/luke/releases/tag/pivot-luke-5.5.0 up. either lukes re-index is not opening or it makes searchcode not being able to read it after re-indexing. Luke can still read the index than.

So guess, we can close it, but storing somewhere in doc that with current version of lucene only luke 5.5.0 can be used

**Comment by boyter** [comment]
Added section to README https://github.com/boyter/searchcode-server/commit/d91b397df62bf263061dd601d356ac6c7e62beaf
