### ISSUE TITLE
folders blacklisting feature

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#71]
Would be great to be able to exclude specific folders like \lost+found\ or \bin\ from indexing

Thanks

**Comment by boyter** [comment]
Sounds like a reasonable proposal. 

The way I see this working is that a blacklisted folder option would be added to searchcode.properties such as

directory_black_list=bin,lost+found,target 

And that if the following folders are encountered their contents will not be indexed,

./myproject/bin/
./myproject/something/bin/
./myproject/bin/target/
./myproject/lost+found/
./myproject/target/
./myproject/myproject/target/

Does this look like what you are trying to achieve? Or are you trying to do something that I have not catered for above?

**Comment by quasarea** [comment]
sounds good, case insensitive would be great

**Comment by boyter** [comment]
Not sure if I agree with case insensitive though. What I will do is add an option to enable it to be turned on. By default I will set it to false though.

**Comment by quasarea** [comment]
If you want to be fancy, you could build it based on https://git-scm.com/docs/gitignore as they have pretty comprehensive solution around that.

You have something you could build on already in helpers class (sorry, I'm not java dev but your project makes me want to write some code there ;p)

`   /**
     * Generic file paths that should be ignored
     */
    public static boolean ignoreFiles(String fileParent) {
        if (fileParent.endsWith("/.git") || fileParent.contains("/.git/") || fileParent.contains(".git/") || fileParent.equals(".git")) {
            return true;
        }

        if (fileParent.endsWith("/.svn") || fileParent.contains("/.svn/")) {
            return true;
        }

        return false;
    }`

**Comment by boyter** [comment]
I actaully have already added it in that exact spot actually :)

https://github.com/boyter/searchcode-server/blob/refactor/src/main/java/com/searchcode/app/util/Helpers.java#L170

Just running though the standard integration tests before merging in is all.

**Comment by boyter** [comment]
Resolved. Will make it into the next release.
