### ISSUE TITLE
dynamic language mapping

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#75]
Would be great if language mapping could be loaded from searchcode.sqlite or searchcode.properties rather than hardcoded.

You could take a look at https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

**Comment by boyter** [comment]
Already done for the next release. However it is stored as the OWASP data as a JSON file on disk. Incidentally this file is published under creative commons as well.

https://github.com/boyter/searchcode-server/issues/56
