### ISSUE TITLE
binary extensions

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#76]
Those extensions I found in sources that I use (and some in soucecode sources) and are binary:
*woff,eot,cur,dm,xpm,emz,db,scc,idx,mpp,dot,pspimage,stl,dml,wmf,rvm,resources,tlb,msg,vsd,chm,fm,book,dgn,blines,cab,lib
* docx,doc,xls,xlsx,ppt,pptx,

**Comment by boyter** [comment]
Would it be possible for you to open a pull request for this one? Just modify the https://github.com/boyter/searchcode-server/blob/master/searchcode.properties.example file in a fork and send it though. Thats the one that actually makes it into binary releases.

Or if you could just post the exact format you use here that would work too.

**Comment by quasarea** [comment]
Here is raw copy&paste

`binary_extension_black_list=woff,eot,cur,dm,xpm,emz,db,scc,idx,mpp,dot,pspimage,stl,dml,wmf,rvm,resources,tlb,docx,doc,xls,xlsx,ppt,pptx,msg,vsd,chm,fm,book,dgn,blines,cab,lib,obj,jar,pdb,dll,bin,out,elf,so,msi,nupkg,pyc,ttf,woff2,jpg,jpeg,png,gif,bmp,psd,tif,tiff,yuv,ico,xls,xlsx,pdb,pdf,apk,com,exe,bz2,7z,tgz,rar,gz,zip,zipx,tar,rpm,bin,dmg,iso,vcd,mp3,flac,wma,wav,mid,m4a,3gp,flv,mov,mp4,mpg,rm,wmv,avi,m4v,sqlite,class
`

I was not sure about doc files, as they have some readable value inside, but finally I decided to exclude them, as I strongly believe that no documentation should be stored in doc files.

**Comment by boyter** [comment]
https://github.com/boyter/searchcode-server/blob/master/searchcode.properties.example#L32

Done.
