### ISSUE TITLE
Move "Filter Results" under filter options

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#80]
I would reorganise filters panel a bit, as it seems counter intuitive to have buttons on top. Use flow from top to bottom and than you require to go back to the top to click apply

I attached example what I have now and what I think would be a bit better.

![2017_03_16_12_24_16_search_for_make_](https://cloud.githubusercontent.com/assets/10334982/23999126/4a49c622-0a4f-11e7-9341-909c760b2ba8.png)

**Comment by boyter** [comment]
Looks reasonable. With the collapsed view its not an issue at all.

**Comment by boyter** [comment]
Resolved.
