### ISSUE TITLE
language matching uses only first word

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#86]
if I have two languages like Fortran 77 and Fortran 90, I cannot filter on Fortran 90 becasue query like this

http://localhost:8080/?q=a&lan=Fortran%2090 

checks proper Fortran 90 in filter section, but yields results for Fortran 77 results only.

**Comment by boyter** [comment]
Seems to be an issue with the filters expecting a whole value and not with a space. Might need to look at storing the representation with a - or _ for this. Sadly will require a reindex.

**Comment by boyter** [comment]
Resolved in 797307a789f80d90247d1dee11440f0a2efc4c1a
