### ISSUE TITLE
I'm a puzzled about the variable of "RepoGitLocation" ， i would be appreciate it you can explain which location does it stand for.   

### ISSUE THREAD

**Issue by zhuzhujulie** [boyter/searchcode-server#90]

**Comment by boyter** [comment]
Could you be more specific where it is?

**Comment by zhuzhujulie** [comment]
Yes, In fact, i'm reading your code recently, in the source code, you define a variable, and i don't understand.
the location of this variable:
package: com.searchcode.app.jobs.repository----->class: IndexBaseRepoJob----->method: execute
------->code: String repoGitLocation = repoLocations + "/" + repoName + "/.git/";

**Comment by boyter** [comment]
Oh dear. I am sorry for the state of some of it. That is also the worst written file as well. It really needs some serious refactoring (which I am in the middle of doing).

That variable is literally just for checking the existence of the .git directory which would indicate that there is a git repository there. It then tries to just update it the repository.

```
String repoGitLocation = repoLocations + "/" + repoResult.getName() + "/.git/";

File file = new File(repoGitLocation);
boolean existingRepo = file.exists();
```
The third line is the actual check.

**Comment by zhuzhujulie** [comment]
yeah,
i know what does the existingRepo stand for
but In fact, I'm actually puzzled about code below:
             
   // If the last index was not sucessful, then trigger full index
         boolean indexsuccess = checkIndexSucess(repoGitLocation);

it says for checking whether it is indexed successfully, does it mean checking for the existing of indexsuccess directory,  if so, i think maybe we should use this argument:   repoLocations+"/"+repoName
and i don't know why you use the argument of repoGitLocation.

**Comment by boyter** [comment]
Its probably just a hangover from the many rewrites of that logic. Its possible as you say that it is wrong. Refactoring that piece of code is still a work in progress.

**Comment by boyter** [comment]
Going to close this down as it is something that is in the middle of being refactored.
