### ISSUE TITLE
pom.xml missing <version> tag 

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#93]
hi, 

two plugins have no version defined in pom.xml
* compiler
* surefire
```
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.6.1</version>
```
and 
```
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.19.1</version>
```

**Comment by boyter** [comment]
Should investigate this.

**Comment by quasarea** [comment]
without version information, maven will not download those plugins, so you want be able to run tests

**Comment by boyter** [comment]
I added using what you have above. Seems to be all good.

fd08d517c1b76c935f4b1973c25c0b9935f7897e
